# Hoja de Trabajo Práctico Nº 1: Geometría de Rotación, Dualidad de SO(3) y Composición
**Materia:** Robótica (IMT-342) - UCB Sede Tarija  
**Docente:** M.Sc. Ing. Bernardo Quiroga Turdera  
**Estudiante:** Florencia Frigerio  
**Fecha:** 13 de Agosto, 2026  

---

## Ejercicio 1: Análisis de la Dualidad Activa vs. Pasiva (Teoría)

### Caso A (Transformación Activa)
Dado el vector $p = [1, 2, 0]^T$ y la matriz de rotación $R_z(90^\circ)$:
$$R_z(90^\circ) = \begin{bmatrix} 0 & -1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix}$$
Calculando $p' = R_z(90^\circ) \cdot p$:
$$p' = \begin{bmatrix} 0 & -1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix} \begin{bmatrix} 1 \\ 2 \\ 0 \end{bmatrix} = \begin{bmatrix} -2 \\ 1 \\ 0 \end{bmatrix}$$

### Caso B (Transformación Pasiva)
Si $p_B = [1, 2, 0]^T$ y $\{B\}$ está rotado $90^\circ$ respecto a $\{A\}$ alrededor de $Z_A$:
$$^A R_B = R_z(90^\circ) \implies p_A = ^A R_B \cdot p_B = \begin{bmatrix} -2 \\ 1 \\ 0 \end{bmatrix}$$

---

## Ejercicio 2: Composición de Rotaciones (Ejes Fijos vs. Móviles)
1. Gira $45^\circ$ alrededor del eje $X_A$ fijo $\rightarrow R_x(45^\circ)$
2. Gira $90^\circ$ alrededor del eje $Z_B$ móvil $\rightarrow R_z(90^\circ)$
3. Gira $-45^\circ$ alrededor del eje $Y_A$ fijo $\rightarrow R_y(-45^\circ)$

Ecuación de multiplicación de composición:
$$^A R_B = R_y(-45^\circ) \cdot R_x(45^\circ) \cdot R_z(90^\circ)$$


### Demostración Manuscrita / Gráficos:
![Ejercicio 1 - Análisis de Dualidad](img1.jpej)



![Ejercicio 1 - Análisis de Dualidad](img1.jpeg)

In [6]:
![Ejercicio 1 - Análisis de Dualidad](img2.jpeg)

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `[Ejercicio 1 - Análisis de Dualidad](img2.jpeg)'


![Ejercicio 2 - Análisis de Dualidad](img2.jpeg)

In [8]:
![Ejercicio 2](img3.jpeg)

/bin/bash: -c: line 1: syntax error near unexpected token `('
/bin/bash: -c: line 1: `[Ejercicio 2](img3.jpeg)'


![Ejercicio 3 - Análisis de Dualidad](img3.jpeg)

![Ejercicio 2 - Análisis de Dualidad](img4.jpeg)

In [1]:
import numpy as np

def rot_x(deg):
    """Rotación elemental alrededor del eje X, ángulo en grados."""
    t = np.radians(deg)
    c, s = np.cos(t), np.sin(t)
    return np.array([
        [1, 0,  0],
        [0, c, -s],
        [0, s,  c]
    ])

def rot_y(deg):
    """Rotación elemental alrededor del eje Y, ángulo en grados."""
    t = np.radians(deg)
    c, s = np.cos(t), np.sin(t)
    return np.array([
        [ c, 0, s],
        [ 0, 1, 0],
        [-s, 0, c]
    ])

def rot_z(deg):
    """Rotación elemental alrededor del eje Z, ángulo en grados."""
    t = np.radians(deg)
    c, s = np.cos(t), np.sin(t)
    return np.array([
        [c, -s, 0],
        [s,  c, 0],
        [0,  0, 1]
    ])

# --- 2. Composición: A_R_B del Ejercicio 2 ---
# Regla: eje fijo -> premultiplica | eje móvil -> postmultiplica
# 1) Rx(45)  fijo   -> C1 = Rx(45)
# 2) Rz(90)  móvil  -> C2 = C1 @ Rz(90)   (postmultiplica)
# 3) Ry(-45) fijo   -> C3 = Ry(-45) @ C2  (premultiplica)

C1 = rot_x(45)
C2 = C1 @ rot_z(90)
A_R_B = rot_y(-45) @ C2

print("A_R_B =\n", A_R_B)

# --- 3. Validación: ortogonalidad vía norma de Frobenius ---
I = np.eye(3)
error_frobenius = np.linalg.norm(A_R_B.T @ A_R_B - I, ord='fro')
print(f"\n||R^T R - I||_F = {error_frobenius:.2e}")
assert error_frobenius < 1e-15, "La matriz no es ortogonal dentro de la tolerancia"
print("✓ Ortogonalidad verificada (R^T R = I)")

# --- 4. Validación: isometría (conservación de la norma) ---
p_B = np.array([2, -1, 4])
p_A = A_R_B @ p_B

norm_diff = np.linalg.norm(p_A) - np.linalg.norm(p_B)
print(f"\np_B = {p_B},  ||p_B|| = {np.linalg.norm(p_B):.6f}")
print(f"p_A = {p_A},  ||p_A|| = {np.linalg.norm(p_A):.6f}")
print(f"||p_A|| - ||p_B|| = {norm_diff:.2e}")
assert abs(norm_diff) < 1e-14, "La rotación no conservó la norma"
print("✓ Isometría verificada (la rotación conserva la magnitud del vector)")

A_R_B =
 [[-5.00000000e-01 -7.07106781e-01 -5.00000000e-01]
 [ 7.07106781e-01  4.32978028e-17 -7.07106781e-01]
 [ 5.00000000e-01 -7.07106781e-01  5.00000000e-01]]

||R^T R - I||_F = 1.36e-16
✓ Ortogonalidad verificada (R^T R = I)

p_B = [ 2 -1  4],  ||p_B|| = 4.582576
p_A = [-2.29289322 -1.41421356  3.70710678],  ||p_A|| = 4.582576
||p_A|| - ||p_B|| = 0.00e+00
✓ Isometría verificada (la rotación conserva la magnitud del vector)
